apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: obs-client
data:
  COLLECTOR_ID: {{ .Values.secret.collectorId | b64enc | quote }}
  CLIENT_ID: {{ .Values.secret.clientId | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.secret.clientSecret | b64enc | quote }}
  TOKEN_URL: {{ .Values.secret.tokenUrl | b64enc | quote }}
  OTLP_ENDPOINT: {{ .Values.secret.otlpEndpoint | b64enc | quote }}