apiVersion: v1
kind: Service
metadata:
  name: {{ include "traffic-collector-chart.fullname" . }}
  labels:
    {{- include "traffic-collector-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: service-port
      protocol: TCP
      name: grpc
    - port: 8888
      targetPort: metrics-port
      protocol: TCP
      name: http
  selector:
    {{- include "traffic-collector-chart.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "traffic-collector-chart.fullname" . }}-cluster-service
  labels:
    {{- include "traffic-collector-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: service-port
      protocol: TCP
      name: grpc
    - port: 8888
      targetPort: metrics-port
      protocol: TCP
      name: http
  selector:
    {{- include "traffic-collector-chart.selectorLabels" . | nindent 4 }}