- name: Setup Astra Mirroring using Docker Compose
  hosts:
  remote_user:

  vars:
    image_tag: latest  # Default Docker image tag
    remote_base_path: ~/astra-mirroring/
    mirror_settings_path: ""  # Path to local mirror-settings.json file
    env_file_path: ""  # Path to local .env file

  tasks:
    # Ensure the directory exists
    - name: Ensure the directory exists
      file:
        path: "{{ remote_base_path }}"
        state: directory
        mode: '0755'

    # Copy configuration files to the target machine
    - name: Copy mirror-settings.json and .env
      copy:
        src: "{{ item }}"
        dest: "{{ remote_base_path }}{{ item | basename }}"
        mode: '0644'
      with_items:
        - "{{ mirror_settings_path }}"
        - "{{ env_file_path }}"

    # Start Astra Mirroring container using inline Docker Compose
    - name: Start Astra Mirroring container
      docker_compose:
        definition:
          version: '3.8'
          services:
            astra-mirroring:
              image: getastra/mirroring:{{ image_tag }}
              container_name: getastra-mirroring-container
              network_mode: host
              volumes:
                - "{{ remote_base_path }}/mirror-settings.json:/root/obs-integ/mirror-settings.json"
              env_file:
                - "{{ remote_base_path }}/.env"
              restart: always
        state: present