- name: Upgrade Docker Container using Docker Compose
  hosts: gcp_instances

  vars:
    image_tag: latest  # Default to 'latest' if not specified
    compose_file: docker-compose.yml  
    remote_base_path: ~/astra-mirroring/  # Target path where docker-compose.yml and other files are located
    mirror_settings_path: ""  # Path to mirror-settings.json file (use playbook directory as base)
    env_file_path: ""  # Path to .env file (use playbook directory as base)

  tasks:
    # Ensure the directory ~/astra-mirroring exists on the target machine
    - name: Ensure directory ~/astra-mirroring exists
      file:
        path: "{{ remote_base_path }}"
        state: directory
        mode: '0755'
      become: no  # No need for sudo for user directories

    # Copy the updated mirror-settings.json and .env files to ~/astra-mirroring/ if needed
    - name: Copy updated mirror-settings.json and .env files
      copy:
        src: "{{ item }}"
        dest: "{{ remote_base_path }}{{ item | basename }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      with_items:
        - "{{mirror_settings_path}}"
        - "{{env_file_path}}"
      become: no  # No need for sudo for copying files

    # Pull the latest Docker image using Docker Compose
    - name: Pull the latest Docker image using Docker Compose
      shell: |
        docker compose -f {{ remote_base_path }}{{ compose_file }} pull
      args:
        executable: /bin/bash
      become: yes  # Requires sudo for Docker Compose

    # Restart the Docker container using Docker Compose to apply the new image
    - name: Restart Docker container using Docker Compose
      shell: |
        docker compose -f {{ remote_base_path }}{{ compose_file }} up -d
      args:
        executable: /bin/bash
      become: yes  # Requires sudo to restart containers with Docker Compose
      